# Generated by Django 5.1.5 on 2025-02-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_rename_base_img_pettype_base_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pettype",
            name="base_image",
            field=models.ImageField(upload_to="pet_imgs/"),
        ),
    ]
