# Generated by Django 5.1.6 on 2025-02-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="name",
            field=models.CharField(
                default="Group Name", help_text="The display name for the group", max_length=100
            ),
            preserve_default=False,
        ),
    ]
