# Generated by Django 5.1.6 on 2025-02-17 20:21

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "code",
                    models.CharField(
                        default=users.models.generate_unique_code,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "group_admin",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin for the group. Must be a member of the group.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administered_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
