# Generated by Django 5.1.7 on 2025-03-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
