# Generated by Django 5.1.6 on 2025-02-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="longitude",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
