# Generated by Django 5.1.6 on 2025-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="users.profile"),
        ),
    ]
