# Generated by Django 5.1.6 on 2025-02-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_latitude_profile_longitude_alter_profile_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "title",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("hover_text", models.CharField(max_length=100)),
                ("colour", models.CharField(default="#FF0000", max_length=7)),
            ],
        ),
    ]
