# Generated by Django 5.1.6 on 2025-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_remove_pet_points"),
        ("users", "0002_profile_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="owned_accessories",
            field=models.ManyToManyField(blank=True, to="pets.cosmetic"),
        ),
        migrations.AddField(
            model_name="profile",
            name="pet_bucks",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
