# Generated by Django 5.1.5 on 2025-02-23 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_usergroup_name 2"),
        ("users", "0002_usergroup_name"),
    ]

    operations = []
