# Generated by Django 5.1.6 on 2025-02-12 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="rarity",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
