# Generated by Django 5.1.6 on 2025-02-12 21:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_badgeinstance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="badgeinstance",
            unique_together={("user", "badge")},
        ),
    ]
