# Generated by Django 5.1.6 on 2025-03-01 20:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CosmeticType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PetType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("base_image", models.ImageField(upload_to="pets/base_imgs/")),
            ],
        ),
        migrations.CreateModel(
            name="Cosmetic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pets.cosmetictype",
                    ),
                ),
                ("fits", models.ManyToManyField(to="pets.pettype")),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "health",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("cosmetics", models.ManyToManyField(blank=True, to="pets.cosmetic")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pets.pettype"
                    ),
                ),
            ],
        ),
    ]
