# Generated by Django 5.1.6 on 2025-03-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="points",
        ),
    ]
