# Generated by Django 5.1.6 on 2025-02-11 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pettype',
            old_name='base_img',
            new_name='base_image',
        ),
        migrations.AlterField(
            model_name='pettype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.pettype')),
            ],
        ),
    ]
