# Generated by Django 5.1.6 on 2025-02-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
