# Generated by Django 5.1.6 on 2025-02-14 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_rename_base_img_pettype_base_image_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CosmeticType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("X Position", models.FloatField()),
                ("Y Position", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="pet",
            name="points",
        ),
        migrations.RemoveField(
            model_name="pettype",
            name="base_image",
        ),
        migrations.AddField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pettype",
            name="Base Image",
            field=models.ImageField(default="", upload_to="pets/base_imgs/"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Cosmetic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("fits", models.ManyToManyField(to="pets.pettype")),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pets.cosmetictype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pet",
            name="cosmetics",
            field=models.ManyToManyField(blank=True, to="pets.cosmetic"),
        ),
    ]
