# Generated by Django 5.1.5 on 2025-02-23 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_pet_points 2"),
        ("pets", "0003_alter_pet_owner 2"),
        ("pets", "0004_alter_pettype_name 2"),
        ("pets", "0004_alter_pettype_name"),
    ]

    operations = []
