# Generated by Django 5.1.6 on 2025-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petreal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactiontype",
            name="icon",
            field=models.CharField(max_length=5),
        ),
    ]
