# Generated by Django 5.1.6 on 2025-03-10 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petReal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userphoto",
            name="id",
        ),
        migrations.AlterField(
            model_name="reactiontype",
            name="icon",
            field=models.CharField(
                max_length=3, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="reactiontype",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userphoto",
            name="user_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="UserPhoto",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userphotoreaction",
            name="reacted_photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="petReal.userphoto"
            ),
        ),
        migrations.AlterField(
            model_name="userphotoreaction",
            name="reactor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
