# Generated by Django 5.1.6 on 2025-03-07 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petreal", "0002_alter_reactiontype_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userphotoreaction",
            old_name="user_photo_id",
            new_name="reactor",
        ),
        migrations.AddField(
            model_name="userphotoreaction",
            name="reacted_photo",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserPhotoReaction",
                to="petreal.userphoto",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reactiontype",
            name="icon",
            field=models.CharField(max_length=3),
        ),
    ]
