# Generated by Django 5.1.6 on 2025-02-06 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("colour", models.CharField(default="#000000", max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="IndividualFeature",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.feature",
                    ),
                ),
            ],
        ),
    ]
