# Generated by Django 5.1.6 on 2025-02-09 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("colour", models.CharField(default="#000000", max_length=7)),
                (
                    "generic_img",
                    models.ImageField(upload_to="locations/generic_feature_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationsAppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_lat", models.FloatField(default=0.0)),
                ("min_lon", models.FloatField(default=0.0)),
                ("max_lat", models.FloatField(default=0.1)),
                ("max_lon", models.FloatField(default=0.1)),
                ("min_world_x", models.FloatField(default=0.0)),
                ("min_world_y", models.FloatField(default=0.0)),
                ("min_world_z", models.FloatField(default=0.0)),
                ("max_world_x", models.FloatField(default=0.1)),
                ("max_world_y", models.FloatField(default=0.1)),
                ("max_world_z", models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name="Map3DChunk",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="locations/3d_map_chunks/")),
                ("file_original_name", models.CharField(max_length=200)),
                ("center_lat", models.FloatField(default=0)),
                ("center_lon", models.FloatField(default=0)),
                ("bottom_left_lat", models.FloatField(default=0)),
                ("bottom_left_lon", models.FloatField(default=0)),
                ("top_right_lat", models.FloatField(default=0)),
                ("top_right_lon", models.FloatField(default=0)),
                ("bottom_left_x", models.FloatField(default=0)),
                ("bottom_left_y", models.FloatField(default=0)),
                ("bottom_left_z", models.FloatField(default=0)),
                ("top_right_x", models.FloatField(default=0)),
                ("top_right_y", models.FloatField(default=0)),
                ("top_right_z", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="IndividualFeature",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                (
                    "specific_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="locations/specific_feature_images/",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.feature",
                    ),
                ),
            ],
        ),
    ]
