# Generated by Django 5.1.6 on 2025-02-11 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("colour", models.CharField(default="#000000", max_length=7)),
                (
                    "generic_img",
                    models.ImageField(upload_to="locations/feature_type_img/"),
                ),
                (
                    "feature_mesh",
                    models.FileField(
                        blank=True, null=True, upload_to="locations/feature_mesh/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationsAppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_lat", models.FloatField(default=0.2)),
                ("min_lon", models.FloatField(default=0.2)),
                ("max_lat", models.FloatField(default=0.1)),
                ("max_lon", models.FloatField(default=0.1)),
                ("min_world_x", models.FloatField(default=0.2)),
                ("min_world_y", models.FloatField(default=0.2)),
                ("min_world_z", models.FloatField(default=0.2)),
                ("max_world_x", models.FloatField(default=0.1)),
                ("max_world_y", models.FloatField(default=0.1)),
                ("max_world_z", models.FloatField(default=0.1)),
                (
                    "camera_z_map",
                    models.ImageField(
                        blank=True, null=True, upload_to="locations/camera_z_map/"
                    ),
                ),
                ("world_colour", models.CharField(default="#000000", max_length=7)),
                ("render_dist", models.IntegerField(default=250)),
            ],
        ),
        migrations.CreateModel(
            name="Map3DChunk",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="locations/3d_map_chunks/")),
                ("file_original_name", models.CharField(max_length=200)),
                ("center_lat", models.FloatField(default=0)),
                ("center_lon", models.FloatField(default=0)),
                ("bottom_left_lat", models.FloatField(default=0)),
                ("bottom_left_lon", models.FloatField(default=0)),
                ("top_right_lat", models.FloatField(default=0)),
                ("top_right_lon", models.FloatField(default=0)),
                ("bottom_left_x", models.FloatField(default=0)),
                ("bottom_left_y", models.FloatField(default=0)),
                ("bottom_left_z", models.FloatField(default=0)),
                ("top_right_x", models.FloatField(default=0)),
                ("top_right_y", models.FloatField(default=0)),
                ("top_right_z", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionFeature",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question_text", models.TextField()),
                ("case_sensitive", models.BooleanField(default=False)),
                ("use_fuzzy_comparison", models.BooleanField(default=False)),
                ("fuzzy_threshold", models.IntegerField(default=65)),
            ],
        ),
        migrations.CreateModel(
            name="FeatureInstance",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                (
                    "specific_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="locations/feature_instance_img/",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.featuretype",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.questionfeature",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeatureInstanceTileMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.featureinstance",
                    ),
                ),
                (
                    "map_chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.map3dchunk",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.questionfeature",
                    ),
                ),
            ],
        ),
    ]
