# Generated by Django 5.1.6 on 2025-02-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationsappsettings",
            name="default_lat",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="locationsappsettings",
            name="default_lon",
            field=models.FloatField(default=0),
        ),
    ]
