# Generated by Django 5.1.6 on 2025-02-09 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("colour", models.CharField(default="#000000", max_length=7)),
                (
                    "generic_img",
                    models.ImageField(upload_to="locations/feature_type_img/"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="individualfeature",
            name="feature",
        ),
        migrations.AlterField(
            model_name="locationsappsettings",
            name="min_lat",
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name="locationsappsettings",
            name="min_lon",
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name="locationsappsettings",
            name="min_world_x",
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name="locationsappsettings",
            name="min_world_y",
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name="locationsappsettings",
            name="min_world_z",
            field=models.FloatField(default=0.2),
        ),
        migrations.CreateModel(
            name="FeatureInstance",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                (
                    "specific_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="locations/feature_instance_img/",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.featuretype",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Feature",
        ),
        migrations.DeleteModel(
            name="IndividualFeature",
        ),
    ]
