# Generated by Django 5.1.6 on 2025-02-11 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featureinstance",
            name="question",
        ),
        migrations.AddField(
            model_name="questionfeature",
            name="feature",
            field=models.ForeignKey(
                default="test",
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.featureinstance",
            ),
            preserve_default=False,
        ),
    ]
