# Generated by Django 5.1.6 on 2025-03-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureinstance",
            name="instance_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
