# Generated by Django 5.1.6 on 2025-02-12 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_remove_featureinstance_question_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationsappsettings",
            options={"verbose_name_plural": "Map Settings"},
        ),
    ]
