# Generated by Django 5.1.6 on 2025-02-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_featuretype_remove_individualfeature_feature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationsappsettings",
            name="camera_z_map",
            field=models.ImageField(
                blank=True, null=True, upload_to="locations/camera_z_map/"
            ),
        ),
    ]
