# Generated by Django 5.1.6 on 2025-02-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_remove_featureinstance_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureinstance",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="locations/qr_codes/"
            ),
        ),
        migrations.AddField(
            model_name="locationsappsettings",
            name="qr_prefix",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
