# Generated by Django 5.1.7 on 2025-03-19 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lootboxes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LootBox",
        ),
    ]
