# Generated by Django 5.1.6 on 2025-02-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeaturereach",
            name="extra",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
