# Generated by Django 5.1.6 on 2025-02-13 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="streak",
            old_name="count",
            new_name="raw_count",
        ),
    ]
