# Generated by Django 5.1.7 on 2025-03-19 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengesettings",
            name="health_depreciation_amount",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="challengesettings",
            name="health_depreciation_interval",
            field=models.DurationField(default=datetime.timedelta(seconds=21600)),
        ),
    ]
