# Generated by Django 5.1.7 on 2025-03-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "challenges",
            "0002_alter_challengesettings_health_depreciation_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengesettings",
            name="question_feature_points",
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name="challengesettings",
            name="reached_feature_points",
            field=models.IntegerField(default=20),
        ),
    ]
