# Generated by Django 5.1.6 on 2025-02-13 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_rename_count_streak_raw_count"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StreakSettings",
            new_name="ChallengeSettings",
        ),
        migrations.AlterModelOptions(
            name="challengesettings",
            options={"verbose_name_plural": "Challenge Settings"},
        ),
    ]
