# Generated by Django 5.1.6 on 2025-02-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
